### ISSUE TITLE
Better error messages when forgetting @Received, @Instantiated or @Forwarded for @Instantiable class

### ISSUE THREAD

**Issue by tareksabry1337** [dfed/SafeDI#53]
**Goals**
Currently if a a class is marked as @.Instantiable and its dependencies are not marked as @.Received, @.Instantiated or @.Forwarded the compiler fails with a generic error saying that it's missing a public initializer

<img width="1280" alt="image" src="https://github.com/dfed/SafeDI/assets/45688300/01e0d03b-8435-4431-a808-f3e145b52cb7">

We need the compiler to be more vocal about the missing requirements because error messages like these can be really confusing

**Comment by dfed** [comment]
Do you have suggested wording? Right now we are:
* telling you that you are missing an initializer comprising all injected properties – in this case you have no injected properties
* providing a FixIt that creates an initializer method that shows you which properties are not injected

Maybe we should have a special-cased error message for zero dependencies? Something like:
```
@Instantiable-decorated type with no injected properties must have `public` or `open` initializer that takes no parameters
```

Let me know if you think that would help. It's possible I've missed what was confusing.

Regardless, I should fix that the error message says "parameters" rather than "properties". That's very much my bad.

**Comment by tareksabry1337** [comment]
The thing is that I have an initializer that has all the dependencies required for the class to function and none of them were marked with the mentioned property decorators, hence the confusion (I have a public initializer that satisfies what I need, what I'm missing?) and doing fix it for me just creates an empty initializer that takes no parameters.

What I think is ideal should be a message that points out which dependencies from the class are missing property decorators (@Received, @Instantiated or @Forwarded)

**Comment by dfed** [comment]
The issue is that SafeDI can't know that the developer intended to inject properties but forgot! In #54 I attempted to make the error message explicitly mention that the developer did not mark any properties as injected. I'd love to get your thoughts on that approach and wording.
