### ISSUE TITLE
nonisloated init produces warning on classes decorated with @MainActor

### ISSUE THREAD

**Issue by MrAdamBoyd** [dfed/SafeDI#65]
**Steps to reproduce**
1. Upgrade to Xcode 15.3
2. Try to build

**Sample code or sample project upload**
```
@MainActor
@Instantiable
public final class ApplicationCoordinator: NSObject {
    private(set) var window: UIWindow?

    // MARK: - Initializers
    nonisolated
    public init(
        featureFlagManager: FeatureFlagManager
    ) {
        self.featureFlagManager = featureFlagManager
        super.init()
        // Do other work here
    }

    @Instantiated
    private let featureFlagManager: FeatureFlagManager
```

Now results in an error:
`Main actor-isolated property featureFlagManager can not be mutated from a non-isolated context; this is an error in Swift 6`

**Comment by dfed** [comment]
I think we may need to remove `nonisolated` from our initializers, and add `@MainActor` to the root init if our root is also `@MainActor`. I need to play with this, but it should be doable. Also happy to have help on this one. I'm a few weeks from upgrading to Xcode 15.3 since I have other dependencies that are problematic.

**Comment by dfed** [comment]
Also need to keep track of which builders build main-actor-bound types and mark those closures (and `instantiate` methods) as main-actor too

**Comment by dfed** [comment]
Once #66 lands, I'll be able to tackle this by creating:
```
public final class MainInstantiator<T: Instantiable> { ... }
public final class MainErasedInstantiator<T: Instantiable> { ... }
```

We'll require using a `Main*Instantiator` if any (recursive) child instantiated property is `@MainActor`-bound.

I need to think a bit about how we will try to detect that a type is `@MainActor`-bound, since it is possible for `@MainActor` to be inherited from a superclass or protocol conformance. I am currently leaning towards not trying to detect this, and instead writing good documentation and relying on build errors to guide folk. Once you've made a `Main*Instantiator`, though, we'll know that anything that builds that must also be a `Main*Instantiator`.

**Comment by dfed** [comment]
New naming proposal:

```
public final class Instantiator<T: Instantiable> { ... }
public final class ErasedInstantiator<T: Instantiable> { ... }

public final class UnboundInstantiator<T: Instantiable> { ... }
public final class UnboundErasedInstantiator<T: Instantiable> { ... }
```

In this proposal, we're main-by-default. If you want to be able to instantiate types off of main, you use an `Unbound*Instantiator`.
